### ISSUE TITLE
Not finished but working?

### ISSUE THREAD

**Issue by Fortbruhnite** [deepwn/phpminer#3]
I just found this Miner and saw that it was not finished yet and probably wont ever be since work on it has stopped in 2018.
Does this Miner actually work and is just unfinished or can it not be used at all?

**Comment by evil7** [comment]
Sorry. It's stopped and just to prove that can worked under pure php code. And the function only working with CryptoNight v7.
It's a testing project by teammate to learning crypto coin & miner.
